### ISSUE TITLE
Python3 is not supported

### ISSUE THREAD

**Issue by eprikazc** [upwork/python-upwork#28]
Python3 is not supported
```
pip install python-upwork
Collecting python-upwork
  Downloading python-upwork-1.2.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-nz6qxrn7/python-upwork/setup.py", line 35
        print 'Updating ``upwork/__init__.py`` to version "{0}"'.format(version)
                                                               ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-nz6qxrn7/python-upwork/
```

**Comment by rajasimon** [comment]
Please make #27 merge to master and release that so all the Python 3 lovers get it.

**Comment by mnovozhylov** [comment]
The eluded pull request is already merged.
